run:
  timeout: 3m

output:
  formats:
    - format: colored-line-number

linters-settings:
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 140
    tab-width: 4
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/bird2920/SLOTH-GO)
    skip-generated: true
  misspell:
    locale: US
  goconst:
    min-len: 2
    min-occurrences: 2
  funlen:
    lines: 100
    statements: 50
  dupl:
    threshold: 100

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - unused
    - ineffassign
    - typecheck
    - gocritic
    - gosec
    - gocyclo
    - lll
    - stylecheck
    - misspell
    - unparam
    - whitespace
    - goconst
    - dupl
    - funlen
    - gofmt
    - goimports
    - rowserrcheck
    - nakedret
    - unconvert

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocyclo
  max-issues-per-linter: 0
  max-same-issues: 0